"""Helpers for writing Python-generated TeX macro files."""

from __future__ import annotations

from math import floor, log10
from pathlib import Path
from typing import Mapping


def tex_decimal(value: float, digits: int = 4) -> str:
    """Format a scalar in decimal notation for TeX."""

    return f"{float(value):.{digits}f}"



def tex_percent(value: float, digits: int = 2) -> str:
    """Format a share as a percentage in decimal notation for TeX."""

    return f"{100.0 * float(value):.{digits}f}"



def tex_scientific(value: float, digits: int = 2) -> str:
    """Format a scalar in scientific notation for TeX."""

    v = float(value)
    if v == 0.0:
        return "0"
    exponent = int(floor(log10(abs(v))))
    mantissa = v / (10.0 ** exponent)
    return f"{mantissa:.{digits}f}\\times 10^{{{exponent}}}"



def tex_auto(value: float, digits: int = 4, sci_threshold: float = 1e-3, sci_digits: int = 2) -> str:
    """Format a scalar in a style appropriate for TeX prose."""

    if value == 0.0:
        return "0"
    if abs(float(value)) < sci_threshold:
        return tex_scientific(float(value), digits=sci_digits)
    return tex_decimal(float(value), digits=digits)



def tex_interval(lower: float, upper: float, digits: int = 4) -> str:
    """Format an interval for TeX prose."""

    return f"[{float(lower):.{digits}f},\\ {float(upper):.{digits}f}]"



def write_tex_macros(path: Path, macros: Mapping[str, str]) -> Path:
    """Write a TeX macro file with one command per mapping entry."""

    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["% Auto-generated by the quantitative Python pipeline. Do not edit by hand."]
    for name, value in macros.items():
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
